object Libs {
    const val kotlinCore = "org.jetbrains.kotlin:kotlin-stdlib:${Versions.kotlinVersion}"
    const val androidXCore = "androidx.core:core-ktx:${Versions.androidXCoreVersion}"
    const val appCompat = "androidx.appcompat:appcompat:${Versions.appCompatVersion}"
    const val androidMaterial = "com.google.android.material:material:${Versions.materialVersion}"
    const val constrainLayout = "androidx.constraintlayout:constraintlayout:${Versions.constrainLayoutVersion}"
    const val navgationFragment = "androidx.navigation:navigation-fragment-ktx:${Versions.navgationVersion}"
    const val navgationUi = "androidx.navigation:navigation-ui-ktx:${Versions.navgationVersion}"
    const val lifecycleLivedata = "androidx.lifecycle:lifecycle-livedata-ktx:${Versions.lifecycleVersion}"
    const val lifecycleViewModel = "androidx.lifecycle:lifecycle-viewmodel-ktx:${Versions.lifecycleVersion}"
    const val retrofit2Moshi = "com.squareup.retrofit2:converter-moshi:${Versions.retrofitVersion}"
    const val moshiCore = "com.squareup.moshi:moshi-kotlin:${Versions.moshiVersion}"
    const val roomRuntime = "androidx.room:room-runtime:${Versions.roomVersion}"
    const val roomKtx = "androidx.room:room-ktx:${Versions.roomVersion}"
    const val roomCompiler = "androidx.room:room-compiler:${Versions.roomVersion}"
    const val coroutinesCore = "org.jetbrains.kotlinx:kotlinx-coroutines-core:${Versions.coroutinesVersion}"
    const val coroutinesAndroid = "org.jetbrains.kotlinx:kotlinx-coroutines-android:${Versions.coroutinesVersion}   "
    const val koinCore = "org.koin:koin-core:${Versions.koinVersion}"
    const val koinAndroid = "org.koin:koin-android:${Versions.koinVersion}"
    const val koinScope = "org.koin:koin-android-scope:${Versions.koinVersion}"
    const val koinViewModel = "org.koin:koin-androidx-viewmodel:${Versions.koinVersion}"
    const val multidexCore = "com.android.support:multidex:${Versions.multidexVersion}"
    const val circleImageview = "de.hdodenhof:circleimageview:${Versions.circleImageviewVersion}"
}