object Versions {
    const val kotlinVersion = "1.4.32"
    const val androidXCoreVersion = "1.5.0"
    const val appCompatVersion = "1.3.0"
    const val materialVersion = "1.3.0"
    const val constrainLayoutVersion = "2.0.4"
    const val navgationVersion = "2.3.5"
    const val lifecycleVersion = "2.3.1"
    const val retrofitVersion = "2.9.0"
    const val moshiVersion = "1.9.3"
    const val roomVersion = "2.3.0"
    const val coroutinesVersion = "1.4.2"
    const val koinVersion = "2.1.6"
    const val multidexVersion = "1.0.3"
    const val circleImageviewVersion = "3.1.0"
    const val juintVersion = "4.13.2"
    const val androidxJuintVersion = "1.1.2"
    const val androidxEspressoVersion = "3.3.0"
}